; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "巴哈自動簽到系統"
#define MyAppVersion "0.1.0_Beta"
#define MyAppPublisher "FallMaple"
#define MyAppURL "https://github.com/tony53517230/baha_auto_signin_gui"
#define MyAppExeName "run.vbs"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#ifndef Version
  #define Version = '0.1.0.0';
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D519F2CC-4626-41DA-8EDE-83C075A34F9B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\tony5\baha\LICENSE.md
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\tony5\compile
OutputBaseFilename=AutoBahaInstaller_win_x64_v0.1.0_Beta
SetupIconFile=C:\Users\tony5\baha\AutoBaha.ico
UninstallDisplayIcon={app}\AutoBaha.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
VersionInfoVersion={#Version}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startupicon"; Description: "開機啟動"; GroupDescription: "{cm:AdditionalIcons}"; 

[Files]
Source: "C:\Users\tony5\baha\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\log.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\port"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\service_data.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\time.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\time_is_changed"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\python\*"; DestDir: "{app}\python"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\tony5\baha\static\*"; DestDir: "{app}\static"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\tony5\baha\templates\*"; DestDir: "{app}\templates"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\tony5\baha\accounts_system.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\app.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\AutoBaha.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\baha.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\baha_auto_signin_timer.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\crawler.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tony5\baha\data_processor.py"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\AutoBaha.ico"
Name: "{commonstartup}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\AutoBaha.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent

